CREATE TYPE user_role AS ENUM (
    'ADMINISTRATOR',
    'SUPERVISOR',
    'SUPPORT'
);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS password_hash TEXT NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN role user_role NOT NULL DEFAULT 'ADMINISTRATOR';

UPDATE users
SET role = 'ADMINISTRATOR'
WHERE role IS NULL;